name: "sam-build"
runs:
  using: "composite"
  steps:
    - run: |
        aws cloudformation deploy \
          --stack-name deploy-bucket-${GITHUB_REF#refs/heads/}\
          --region ap-northeast-1 \
          --template-file ./resourses/deployBucket.yml 
      shell: bash